import "./globals.css";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider/theme-provider";
import Header from "@/components/shared/header";

const myFont = localFont({
  src: "../public/fonts/tanha.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({ children }) {

  return (
    <html
      dir="rtl"
      lang="fa"
      suppressHydrationWarning
      className={`w-full h-full antialiased ${myFont.className}`}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
