import "./globals.css";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider/theme-provider";
import Header from "@/components/shared/header";
import { Noto_Sans, Playfair_Display } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/shared/Navbar";

const playfairDisplayHeading = Playfair_Display({subsets:['latin'],variable:'--font-heading'});

const notoSans = Noto_Sans({subsets:['latin'],variable:'--font-sans'});

const myFont = localFont({
  src: "../public/fonts/tanha.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({ children }) {

  return (
    <html
      dir="rtl"
      lang="fa"
      suppressHydrationWarning
      className={cn("w-full", "h-full", "antialiased", myFont.className, "font-sans", notoSans.variable, playfairDisplayHeading.variable)}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <Header /> */}
          <Navbar />
          <main className="">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
