import "./globals.css";
import localFont from "next/font/local";
import { ThemeProvider } from "@teispace/next-themes";
import { getTheme } from "@teispace/next-themes/server";
import Header from "@/components/shared/header";

const myFont = localFont({
  src: "../public/fonts/tanha.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const initialTheme = await getTheme();
  return (
    <html
      dir="rtl"
      lang="fa"
      className={`h-full antialiased ${myFont.className}`}
    >
      <body>
        <ThemeProvider
          attribute="class"
          initialTheme={initialTheme ?? undefined}
        >
          <Header />
          <main className="max-w-4xl mx-auto ">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
